// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions]
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9sm1xKGtja2tWX2JMAZKRx3oqnjXXMWQ',
    appId: '1:489117759244:web:02d782e4613f76d07f7b29',
    messagingSenderId: '489117759244',
    projectId: 'auth-3e126',
    authDomain: 'auth-3e126.firebaseapp.com',
    databaseURL: 'https://auth-3e126-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-3e126.firebasestorage.app',
    measurementId: 'G-4953KRHSVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XtAzvtybd6CLAUfttczlEu8rskpQnck',
    appId: '1:489117759244:android:b659739aee1c03ff7f7b29',
    messagingSenderId: '489117759244',
    projectId: 'auth-3e126',
    databaseURL: 'https://auth-3e126-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-3e126.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9sm1xKGtja2tWX2JMAZKRx3oqnjXXMWQ',
    appId: '1:489117759244:web:2a379ea412d82e8a7f7b29',
    messagingSenderId: '489117759244',
    projectId: 'auth-3e126',
    authDomain: 'auth-3e126.firebaseapp.com',
    databaseURL: 'https://auth-3e126-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'auth-3e126.firebasestorage.app',
    measurementId: 'G-7X6TBGYJZW',
  );

}
